package com.accenture.aris.inventory.business.repository;

import com.accenture.aris.inventory.business.entity.ItemEntity;
import java.util.List;
import org.springframework.stereotype.Repository;

@Repository
public interface ItemRepository {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_item
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_item
     *
     * @mbggenerated
     */
    int insert(ItemEntity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_item
     *
     * @mbggenerated
     */
    int insertSelective(ItemEntity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_item
     *
     * @mbggenerated
     */
    ItemEntity selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_item
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(ItemEntity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_item
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(ItemEntity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_item
     *
     * @mbggenerated Tue Oct 17 10:33:56 CST 2017
     */
    List<ItemEntity> selectByEntity(ItemEntity entity);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_item
     *
     * @mbggenerated Tue Oct 17 10:33:56 CST 2017
     */
    int countByEntity(ItemEntity entity);
}