package com.accenture.aris.inventory.business.repository;

import com.accenture.aris.inventory.business.entity.WarehouseEntity;
import java.util.List;
import org.springframework.stereotype.Repository;

@Repository
public interface WarehouseRepository {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_warehouse
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_warehouse
     *
     * @mbggenerated
     */
    int insert(WarehouseEntity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_warehouse
     *
     * @mbggenerated
     */
    int insertSelective(WarehouseEntity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_warehouse
     *
     * @mbggenerated
     */
    WarehouseEntity selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_warehouse
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(WarehouseEntity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_warehouse
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(WarehouseEntity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_warehouse
     *
     * @mbggenerated Tue Oct 17 10:33:56 CST 2017
     */
    List<WarehouseEntity> selectByEntity(WarehouseEntity entity);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_warehouse
     *
     * @mbggenerated Tue Oct 17 10:33:56 CST 2017
     */
    int countByEntity(WarehouseEntity entity);
}