package com.accenture.aris.inventory.business.entity;

import java.util.Date;
import org.apache.commons.lang3.builder.ReflectionToStringBuilder;
import org.apache.commons.lang3.builder.ToStringStyle;

public class ItemEntity {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_item.id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_item.ean_code
     *
     * @mbggenerated
     */
    private String eanCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_item.title
     *
     * @mbggenerated
     */
    private String title;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_item.region_code
     *
     * @mbggenerated
     */
    private String regionCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_item.language
     *
     * @mbggenerated
     */
    private String language;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_item.number_of_discs
     *
     * @mbggenerated
     */
    private Integer numberOfDiscs;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_item.price
     *
     * @mbggenerated
     */
    private Integer price;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_item.release_date
     *
     * @mbggenerated
     */
    private Date releaseDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_item.package_img_path
     *
     * @mbggenerated
     */
    private String packageImgPath;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_item.id
     *
     * @return the value of t_item.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_item.id
     *
     * @param id the value for t_item.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_item.ean_code
     *
     * @return the value of t_item.ean_code
     *
     * @mbggenerated
     */
    public String getEanCode() {
        return eanCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_item.ean_code
     *
     * @param eanCode the value for t_item.ean_code
     *
     * @mbggenerated
     */
    public void setEanCode(String eanCode) {
        this.eanCode = eanCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_item.title
     *
     * @return the value of t_item.title
     *
     * @mbggenerated
     */
    public String getTitle() {
        return title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_item.title
     *
     * @param title the value for t_item.title
     *
     * @mbggenerated
     */
    public void setTitle(String title) {
        this.title = title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_item.region_code
     *
     * @return the value of t_item.region_code
     *
     * @mbggenerated
     */
    public String getRegionCode() {
        return regionCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_item.region_code
     *
     * @param regionCode the value for t_item.region_code
     *
     * @mbggenerated
     */
    public void setRegionCode(String regionCode) {
        this.regionCode = regionCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_item.language
     *
     * @return the value of t_item.language
     *
     * @mbggenerated
     */
    public String getLanguage() {
        return language;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_item.language
     *
     * @param language the value for t_item.language
     *
     * @mbggenerated
     */
    public void setLanguage(String language) {
        this.language = language;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_item.number_of_discs
     *
     * @return the value of t_item.number_of_discs
     *
     * @mbggenerated
     */
    public Integer getNumberOfDiscs() {
        return numberOfDiscs;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_item.number_of_discs
     *
     * @param numberOfDiscs the value for t_item.number_of_discs
     *
     * @mbggenerated
     */
    public void setNumberOfDiscs(Integer numberOfDiscs) {
        this.numberOfDiscs = numberOfDiscs;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_item.price
     *
     * @return the value of t_item.price
     *
     * @mbggenerated
     */
    public Integer getPrice() {
        return price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_item.price
     *
     * @param price the value for t_item.price
     *
     * @mbggenerated
     */
    public void setPrice(Integer price) {
        this.price = price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_item.release_date
     *
     * @return the value of t_item.release_date
     *
     * @mbggenerated
     */
    public Date getReleaseDate() {
        return releaseDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_item.release_date
     *
     * @param releaseDate the value for t_item.release_date
     *
     * @mbggenerated
     */
    public void setReleaseDate(Date releaseDate) {
        this.releaseDate = releaseDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_item.package_img_path
     *
     * @return the value of t_item.package_img_path
     *
     * @mbggenerated
     */
    public String getPackageImgPath() {
        return packageImgPath;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_item.package_img_path
     *
     * @param packageImgPath the value for t_item.package_img_path
     *
     * @mbggenerated
     */
    public void setPackageImgPath(String packageImgPath) {
        this.packageImgPath = packageImgPath;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_item
     *
     * @mbggenerated Tue Oct 17 10:33:56 CST 2017
     */
    @Override
    public String toString() {
        return ReflectionToStringBuilder.toString(this, ToStringStyle.SHORT_PREFIX_STYLE);
    }
}