package com.accenture.aris.sample.business.entity;

import java.util.Date;
import org.apache.commons.lang3.builder.ReflectionToStringBuilder;
import org.apache.commons.lang3.builder.ToStringStyle;

public class RoleMenuEntity extends Object {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_role_menu.start_date
     *
     * @mbggenerated
     */
    private Date startDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_role_menu.end_date
     *
     * @mbggenerated
     */
    private Date endDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_role_menu
     *
     * @mbggenerated Thu Jul 10 11:58:28 JST 2014
     */
    private String menuId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_role_menu
     *
     * @mbggenerated Thu Jul 10 11:58:28 JST 2014
     */
    private String roleId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_role_menu.start_date
     *
     * @return the value of t_role_menu.start_date
     *
     * @mbggenerated
     */
    public Date getStartDate() {
        return startDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_role_menu.start_date
     *
     * @param startDate the value for t_role_menu.start_date
     *
     * @mbggenerated
     */
    public void setStartDate(Date startDate) {
        this.startDate = startDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_role_menu.end_date
     *
     * @return the value of t_role_menu.end_date
     *
     * @mbggenerated
     */
    public Date getEndDate() {
        return endDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_role_menu.end_date
     *
     * @param endDate the value for t_role_menu.end_date
     *
     * @mbggenerated
     */
    public void setEndDate(Date endDate) {
        this.endDate = endDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_role_menu
     *
     * @mbggenerated Thu Jul 10 11:58:28 JST 2014
     */
    public String getMenuId() {
        return this.menuId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_role_menu
     *
     * @mbggenerated Thu Jul 10 11:58:28 JST 2014
     */
    public void setMenuId(String menuId) {
        this.menuId = menuId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_role_menu
     *
     * @mbggenerated Thu Jul 10 11:58:28 JST 2014
     */
    public String getRoleId() {
        return this.roleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_role_menu
     *
     * @mbggenerated Thu Jul 10 11:58:28 JST 2014
     */
    public void setRoleId(String roleId) {
        this.roleId = roleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_role_menu
     *
     * @mbggenerated Thu Jul 10 11:58:28 JST 2014
     */
    @Override
    public String toString() {
        return ReflectionToStringBuilder.toString(this, ToStringStyle.SHORT_PREFIX_STYLE);
    }
}